language: python
python:
    - "3.6"
# command to install dependencies
addons:
    apt:
        packages:
        - librrd-dev
install:
    - pip install git+git://github.com/kytos/python-openflow.git
    - pip install git+git://github.com/kytos/kytos-napps.git
    - pip install -r requirements.txt -r requirements-dev.txt
    - pip install coveralls
before_script:
    - cd $VIRTUAL_ENV/var/lib/kytos/napps/kytos
    - for app in *; do if [ $app != "of_core" ]; then rm -rf $app; fi; done
    - cd -
# command to run tests
script:
    - coverage run --source=kytos ./setup.py test
notifications:
  irc:
    channels: "irc.freenode.org#kytos"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
after_success:
    coveralls
